/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package id.co.indocyber;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author user
 */
public class DaftarPertanyaanImprove extends javax.swing.JFrame {
//Set <Department> deptList = new HashSet<>();
List <Employee> employeeList;
Set <Department> deptList;
Company com;
Department dept;
double totalGaji;
    /**
     * Creates new form DaftarPertanyaa
     */
    public DaftarPertanyaanImprove() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        kataTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        gajiField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kataTable.setModel(getModel());
        jScrollPane1.setViewportView(kataTable);

        jButton1.setText("Load Data");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Total Gaji");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(gajiField, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(190, 190, 190))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addComponent(gajiField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(249, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     try {
         List <Employee> data = getDataFromFile("D:\\DataBase.txt");
         System.out.println("yes");
         DefaultTableModel tModel = (DefaultTableModel) kataTable.getModel();
//         DefaultTableModel tM = (DefaultTableModel) dapartmenTable.getModel();
         for(Employee wModel : data) {
             Vector row = new Vector();
             row.add(wModel.getName());
             row.add(wModel.getDept().getDeptName());
             row.add(wModel.getEmpCard().getKode());
             row.add(wModel.getEmpCard().getExpiredDate());
             row.add(wModel.getSalary());
             tModel.addRow(row);   
         }
         dept.setEmployees(employeeList);
         String fmTotalGaji = String.format("%,.2f", dept.calculateTotalSalary());
         gajiField.setText(fmTotalGaji);
       
            
     }  catch (IOException ex) {        
            Logger.getLogger(DaftarPertanyaanImprove.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(DaftarPertanyaanImprove.class.getName()).log(Level.SEVERE, null, ex);
        } 
     
// TODO add your handling code here: 
     
// TODO add your handling code here: 
     
// TODO add your handling code here: 
     
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
    private TableModel getModel() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Nama");
        model.addColumn("Nama Departement");
        model.addColumn("Kode Kartu Kredit");
        model.addColumn("tanggal Expired");
        model.addColumn("Jumlah Gaji");
        model.addColumn("gaji Total");
        return model;
    }
    private TableModel getModelDept() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Nama Departement");
        return model;
    }
    private List<Employee> getDataFromFile (String fileName) throws FileNotFoundException, IOException, ParseException {
//        List<WordModel> bankSoal = new ArrayList<>();
//        File file = new File(fileName);
//        FileReader fileReader = new FileReader(file);
//        BufferedReader reader = new BufferedReader(fileReader);
//        String line = null;
//        while((line = reader.readLine()) != null ) {
//            String []sp = line.split(",");
//            WordModel word = new WordModel(sp[0],sp[1]);
//            bankSoal.add(word);
//        }
        
        File file = new File(fileName);
        FileReader fileReader = new FileReader(file);
        BufferedReader reader = new BufferedReader(fileReader);
        employeeList = new ArrayList();
        deptList = new HashSet<>();
        String line = null;
        Employee emp;
        IdCard idCard;
        SimpleDateFormat df = new SimpleDateFormat("dd-MM-yyyy");
        double gaji;
        while ((line = reader.readLine()) != null) {
            String[] split = line.split(",");
            dept = new Department(split[1].trim());
            deptList.add(dept);
            idCard = new IdCard(split[2].trim(), df.parse(split[3].trim()));
            gaji = Double.parseDouble(split[4]);
            emp = new Employee(split[0], dept, idCard, gaji);
            deptList.add(dept);
            employeeList.add(emp);
//            this.deptList.add(dept);
        }
        
        
        return employeeList;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DaftarPertanyaanImprove.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DaftarPertanyaanImprove.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DaftarPertanyaanImprove.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DaftarPertanyaanImprove.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DaftarPertanyaanImprove().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField gajiField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable kataTable;
    // End of variables declaration//GEN-END:variables
}
